name: 打卡

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  #watch:
  #  types: started
  schedule:
     - cron: '0 0,1,8 * * *'

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
          
      # - name: DDDDOCR
       # run: |
        # python3 -m pip install ddddocr
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD}
